# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 23:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, max_length=100)),
                ('publishedDate', models.DateField(default=datetime.date.today)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Documentation & Blog',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('message', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.IntegerField()),
                ('service_type', models.CharField(choices=[('DA', 'Desenvolvimento de Applicativos'), ('DW', 'Desenvolvimento de Websites'), ('DA', 'Design de Applicativos'), ('DJ', 'Desenvolvimento de Jogos'), ('DB', 'Desenvolvimento de Backend'), ('AC', 'Análise de Clientes e Mercados')], default='DA', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(default='', max_length=15)),
                ('message', models.TextField(blank=True, max_length=200)),
                ('tipo_de_servico', models.CharField(default='Geral', max_length=50)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('link', models.URLField(max_length=250)),
                ('image', models.ImageField(max_length=45, upload_to='uploads/partners/')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('photo', models.ImageField(max_length=45, upload_to='uploads/profiles/')),
                ('role', models.CharField(blank=True, max_length=45)),
                ('administrator', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=550)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('slug', models.SlugField(unique=True)),
                ('linkedin', models.URLField(default='https://linkedin/company/angoapp')),
                ('github', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=45, upload_to='uploads/projects/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=15)),
                ('client', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('link', models.CharField(blank=True, max_length=300)),
                ('artwork', models.ImageField(blank=True, max_length=45, upload_to='uploads/projects/')),
                ('featured', models.BooleanField(default=False)),
                ('publishedDate', models.DateTimeField()),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Person')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Projects',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='projectName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Project'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Person'),
        ),
    ]
