# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 04:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, max_length=100)),
                ('publishedDate', models.DateField(default=datetime.date.today)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Documentation & Blog',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('photo', models.ImageField(max_length=45, upload_to='uploads/profiles/')),
                ('role', models.CharField(blank=True, max_length=45)),
                ('administrator', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=550)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=15)),
                ('client', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('details', models.CharField(blank=True, max_length=30)),
                ('artwork', models.ImageField(blank=True, max_length=45, upload_to='uploads/projects/')),
                ('featured', models.BooleanField(default=False)),
                ('publishedDate', models.DateTimeField()),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Person')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Projects',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Person'),
        ),
    ]
