# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='service_type',
            field=models.CharField(choices=[('DA', 'Desenvolvimento de Applicativos'), ('DW', 'Desenvolvimento de Websites'), ('DA', 'Design de Applicativos'), ('DJ', 'Desenvolvimento de Jogos'), ('DB', 'Desenvolvimento de Backend'), ('AC', 'Análise de Clientes e Mercados')], default=' DA', max_length=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='cellphone',
            field=models.CharField(default='', max_length=16),
        ),
    ]
