# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_auto_20171121_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=45, upload_to='uploads/projects/')),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Project')),
            ],
        ),
    ]
