# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_auto_20180302_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
