# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin',
            field=models.URLField(default='https://linkedin/company/angoapp'),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
