# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_auto_20171218_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('message', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.IntegerField()),
                ('service_type', models.CharField(choices=[('DA', 'Desenvolvimento de Applicativos'), ('DW', 'Desenvolvimento de Websites'), ('DA', 'Design de Applicativos'), ('DJ', 'Desenvolvimento de Jogos'), ('DB', 'Desenvolvimento de Backend'), ('AC', 'An\xe1lise de Clientes e Mercados')], default=b'DA', max_length=2)),
            ],
        ),
    ]
