# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_auto_20180302_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, max_length=650),
        ),
    ]
