# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=45)),
                ('link', models.URLField(max_length=250)),
                ('image', models.ImageField(max_length=45, upload_to=b'uploads/partners/')),
            ],
        ),
    ]
