# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_auto_20180307_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='someone@angoapp.com', max_length=254),
        ),
    ]
