# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
